# 1.Data Collection

In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("europe-motorbikes-zenrows.csv")

In [3]:
dataset

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
0,23990,150,218.0,Honda,03/2020,Gasoline,Manual,Demonstration,CBR1000RR-R Fireblade SP,/offers/honda-others-cbr1000rr-r-fireblade-sp-...
1,7500,2871,90.0,BMW F 800 GT,09/2018,Gasoline,Manual,Used,NaN,/offers/bmw-f-800-gt-gasoline-white-f65273c6-6...
2,800,1700,3.0,Nova Motors Retro Star,10/2019,Gasoline,NaN,Used,NaN,/offers/nova-motors-retro-star-gasoline-red-f8...
3,14990,24345,NaN,Aprilia RSV4,03/2016,Gasoline,NaN,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
4,6200,25000,128.0,Kawasaki Ninja ZX-6R,08/2009,Gasoline,NaN,Used,NaN,/offers/kawasaki-ninja-zx-6r-gasoline-blue-2f8...
...,...,...,...,...,...,...,...,...,...,...
34912,17300,10592,125.0,BMW R 1200 RT,04/2018,Gasoline,Manual,Used,R 1200RT LC,/offers/bmw-r-1200-rt-r-1200rt-lc-gasoline-bla...
34913,8500,29000,54.0,Harley-Davidson Iron 883,05/2004,Gasoline,NaN,Used,NaN,/offers/harley-davidson-iron-883-gasoline-blac...
34914,11990,39140,160.0,BMW S 1000 XR,06/2015,NaN,Manual,Used,ABS,/offers/bmw-s-1000-xr-abs-white-6dac336b-e49b-...
34915,8350,11500,56.0,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used,Black mit Garantie,/offers/triumph-bonneville-t100-black-mit-gara...
34916,8500,19000,46.0,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used,NaN,/offers/yamaha-tmax-530-gasoline-black-eeb19fb...

# 2.Data Preprocessing

In [4]:
dataset.shape

(34917, 10)

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34917 entries, 0 to 34916
Data columns (total 10 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price       34917 non-null  int64
 1   mileage     34917 non-null  int64
 2   power       28598 non-null  float64
 3   make_model  34917 non-null  object
 4   date        34917 non-null  object
 5   fuel        31727 non-null  object
 6   gear        12847 non-null  object
 7   offer_type  34917 non-null  object
 8   version     17413 non-null  object
 9   link        34917 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 2.7+ MB

In [6]:
dataset.isnull().sum()

price             0
mileage           0
power          6319
make_model        0
date              0
fuel           3190
gear          22070
offer_type        0
version       17504
link              0
dtype: int64

In [7]:
dataset.describe()

              price       mileage          power
count  3.491700e+04  3.491700e+04   28598.000000
mean   4.568532e+04  2.183175e+04     206.157598
std    4.850120e+06  2.059421e+05    9371.426466
min    1.000000e+00  0.000000e+00       1.000000
25%    6.999000e+03  2.932000e+03      50.000000
50%    9.920000e+03  1.100000e+04      90.000000
75%    1.259000e+04  2.500000e+04     125.000000
max    8.888889e+08  9.999999e+06  913595.000000

In [8]:
dataset.head()

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
0,23990,150,218.0,Honda,03/2020,Gasoline,Manual,Demonstration,CBR1000RR-R Fireblade SP,/offers/honda-others-cbr1000rr-r-fireblade-sp-...
1,7500,2871,90.0,BMW F 800 GT,09/2018,Gasoline,Manual,Used,NaN,/offers/bmw-f-800-gt-gasoline-white-f65273c6-6...
2,800,1700,3.0,Nova Motors Retro Star,10/2019,Gasoline,NaN,Used,NaN,/offers/nova-motors-retro-star-gasoline-red-f8...
3,14990,24345,NaN,Aprilia RSV4,03/2016,Gasoline,NaN,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
4,6200,25000,128.0,Kawasaki Ninja ZX-6R,08/2009,Gasoline,NaN,Used,NaN,/offers/kawasaki-ninja-zx-6r-gasoline-blue-2f8...

In [9]:
dataset["power"].value_counts()

125.0    1594
110.0    1068
95.0      862
48.0      720
160.0     684
         ...
880.0       1
409.0       1
468.0       1
430.0       1
419.0       1
Name: power, Length: 287, dtype: int64

In [10]:
dataset[dataset['power'].isnull()]

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
3,14990,24345,NaN,Aprilia RSV4,03/2016,Gasoline,NaN,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
18,9490,10000,NaN,Kawasaki Versys 650,01/2019,NaN,Manual,Used,GRAND TOURER,/offers/kawasaki-versys-650-grand-tourer-black...
21,9999,0,NaN,Yamaha,01/2021,NaN,NaN,New,TRACER 7,/offers/yamaha-others-tracer-7-grey-6d7af473-3...
23,16690,0,NaN,BMW R nineT,01/2019,NaN,NaN,New,Pure,/offers/bmw-r-ninet-pure-white-f695d424-cf0b-4...
24,1100,60,NaN,Others,09/2018,NaN,Automatic,Used,E-Mover 800W Metallkorb/Kofferraum/Spiegel,/offers/others-others-e-mover-800w-metallkorb-...
...,...,...,...,...,...,...,...,...,...,...
34874,13973,5,NaN,BMW F 750 GS,01/2021,Gasoline,NaN,New,"| Stijlvariant Sport | Comfort, Touring, Dynam...",/offers/bmw-f-750-gs-stijlvariant-sport-comfor...
34880,7000,11727,NaN,KTM 690 Duke,02/2019,Gasoline,NaN,Used,ABS,/offers/ktm-690-duke-abs-gasoline-silver-c99b8...
34883,15750,515,NaN,BMW F 900 XR,01/2021,NaN,NaN,New,NaN,/offers/bmw-f-900-xr-gold-ba7ec500-7214-4498-a...
34888,34385,2464,NaN,Harley-Davidson Street Glide,01/2021,NaN,NaN,Used,FLHXS Spec. 114,/offers/harley-davidson-street-glide-flhxs-spe...
34910,8450,25400,NaN,Yamaha MT-09,09/2015,Gasoline,NaN,Used,TRACER 900,/offers/yamaha-mt-09-tracer-900-gasoline-red-b...

In [11]:
dataset['power'].fillna(dataset['power'].mean(), inplace=True)

In [12]:
dataset

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
0,23990,150,218.000000,Honda,03/2020,Gasoline,Manual,Demonstration,CBR1000RR-R Fireblade SP,/offers/honda-others-cbr1000rr-r-fireblade-sp-...
1,7500,2871,90.000000,BMW F 800 GT,09/2018,Gasoline,Manual,Used,NaN,/offers/bmw-f-800-gt-gasoline-white-f65273c6-6...
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,NaN,Used,NaN,/offers/nova-motors-retro-star-gasoline-red-f8...
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,NaN,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,NaN,Used,NaN,/offers/kawasaki-ninja-zx-6r-gasoline-blue-2f8...
...,...,...,...,...,...,...,...,...,...,...
34912,17300,10592,125.000000,BMW R 1200 RT,04/2018,Gasoline,Manual,Used,R 1200RT LC,/offers/bmw-r-1200-rt-r-1200rt-lc-gasoline-bla...
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,NaN,Used,NaN,/offers/harley-davidson-iron-883-gasoline-blac...
34914,11990,39140,160.000000,BMW S 1000 XR,06/2015,NaN,Manual,Used,ABS,/offers/bmw-s-1000-xr-abs-white-6dac336b-e49b-...
34915,8350,11500,56.000000,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used,Black mit Garantie,/offers/triumph-bonneville-t100-black-mit-gara...
34916,8500,19000,46.000000,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used,NaN,/offers/yamaha-tmax-530-gasoline-black-eeb19fb...

In [13]:
dataset = dataset.drop_duplicates()

In [14]:
dataset

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
0,23990,150,218.000000,Honda,03/2020,Gasoline,Manual,Demonstration,CBR1000RR-R Fireblade SP,/offers/honda-others-cbr1000rr-r-fireblade-sp-...
1,7500,2871,90.000000,BMW F 800 GT,09/2018,Gasoline,Manual,Used,NaN,/offers/bmw-f-800-gt-gasoline-white-f65273c6-6...
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,NaN,Used,NaN,/offers/nova-motors-retro-star-gasoline-red-f8...
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,NaN,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,NaN,Used,NaN,/offers/kawasaki-ninja-zx-6r-gasoline-blue-2f8...
...,...,...,...,...,...,...,...,...,...,...
34911,36500,7000,90.000000,Harley-Davidson Road Glide,09/2019,Gasoline,Manual,Used,NaN,/offers/harley-davidson-road-glide-gasoline-si...
34912,17300,10592,125.000000,BMW R 1200 RT,04/2018,Gasoline,Manual,Used,R 1200RT LC,/offers/bmw-r-1200-rt-r-1200rt-lc-gasoline-bla...
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,NaN,Used,NaN,/offers/harley-davidson-iron-883-gasoline-blac...
34915,8350,11500,56.000000,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used,Black mit Garantie,/offers/triumph-bonneville-t100-black-mit-gara...
34916,8500,19000,46.000000,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used,NaN,/offers/yamaha-tmax-530-gasoline-black-eeb19fb...

In [15]:
dataset[dataset['fuel'].isnull()]

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
18,9490,10000,206.157598,Kawasaki Versys 650,01/2019,NaN,Manual,Used,GRAND TOURER,/offers/kawasaki-versys-650-grand-tourer-black...
21,9999,0,206.157598,Yamaha,01/2021,NaN,NaN,New,TRACER 7,/offers/yamaha-others-tracer-7-grey-6d7af473-3...
23,16690,0,206.157598,BMW R nineT,01/2019,NaN,NaN,New,Pure,/offers/bmw-r-ninet-pure-white-f695d424-cf0b-4...
24,1100,60,206.157598,Others,09/2018,NaN,Automatic,Used,E-Mover 800W Metallkorb/Kofferraum/Spiegel,/offers/others-others-e-mover-800w-metallkorb-...
26,6590,27630,68.000000,Triumph Bonneville T100,06/2009,NaN,NaN,Used,Black,/offers/triumph-bonneville-t100-black-black-42...
...,...,...,...,...,...,...,...,...,...,...
34850,23500,45000,101.000000,Harley-Davidson Road Glide,01/2015,NaN,NaN,Used,CVO ULTRA,/offers/harley-davidson-road-glide-cvo-ultra-g...
34883,15750,515,206.157598,BMW F 900 XR,01/2021,NaN,NaN,New,NaN,/offers/bmw-f-900-xr-gold-ba7ec500-7214-4498-a...
34888,34385,2464,206.157598,Harley-Davidson Street Glide,01/2021,NaN,NaN,Used,FLHXS Spec. 114,/offers/harley-davidson-street-glide-flhxs-spe...
34889,6999,23553,120.000000,Honda CBR 600,05/2010,NaN,NaN,Used,RR9 ED,/offers/honda-cbr-600-rr9-ed-3f200ba3-8ae3-4f3...
34905,8990,17455,135.000000,Triumph Speed Triple 1050,01/2013,NaN,NaN,Used,ABS,/offers/triumph-speed-triple-1050-abs-white-1d...

In [16]:
dataset['fuel'].fillna(dataset['fuel'].mode().sum(), inplace=True)

C:\Users\sony\Anaconda3\envs\AIMLL\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [17]:
dataset.fuel

0        Gasoline
1        Gasoline
2        Gasoline
3        Gasoline
4        Gasoline
           ...
34911    Gasoline
34912    Gasoline
34913    Gasoline
34915    Gasoline
34916    Gasoline
Name: fuel, Length: 29085, dtype: object

In [18]:
dataset[dataset['gear'].isnull()]

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,NaN,Used,NaN,/offers/nova-motors-retro-star-gasoline-red-f8...
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,NaN,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,NaN,Used,NaN,/offers/kawasaki-ninja-zx-6r-gasoline-blue-2f8...
5,1500,3000,1.000000,Aprilia Mojito 50,07/2010,Gasoline,NaN,Used,NaN,/offers/aprilia-mojito-50-gasoline-black-9283e...
6,10500,1,71.000000,Suzuki V-Strom 650,12/2021,Gasoline,NaN,Pre-registered,XT ABS DL 650 XT,/offers/suzuki-v-strom-650-xt-abs-dl-650-xt-ga...
...,...,...,...,...,...,...,...,...,...,...
34907,130,25000,38.000000,Suzuki GT 380,05/1977,Two Stroke Gasoline,NaN,Used,gt,/offers/suzuki-gt-380-gt-two-stroke-gasoline-w...
34908,6000,32000,7.000000,Piaggio MP3 500,02/2018,Gasoline,NaN,Used,NaN,/offers/piaggio-mp3-500-gasoline-grey-831d82ba...
34909,750,9184,3.000000,Piaggio Zip 50,01/2021,Gasoline,NaN,Used,NaN,/offers/piaggio-zip-50-gasoline-blue-ff056abd-...
34910,8450,25400,206.157598,Yamaha MT-09,09/2015,Gasoline,NaN,Used,TRACER 900,/offers/yamaha-mt-09-tracer-900-gasoline-red-b...
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,NaN,Used,NaN,/offers/harley-davidson-iron-883-gasoline-blac...

In [19]:
dataset['gear'].fillna(dataset['gear'].mode().sum(), inplace=True)

C:\Users\sony\Anaconda3\envs\AIMLL\lib\site-packages\pandas\core\generic.py:6392: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [20]:
dataset.gear.mode().sum()

'Manual'

In [21]:
dataset

,price,mileage,power,make_model,date,fuel,gear,offer_type,version,link
0,23990,150,218.000000,Honda,03/2020,Gasoline,Manual,Demonstration,CBR1000RR-R Fireblade SP,/offers/honda-others-cbr1000rr-r-fireblade-sp-...
1,7500,2871,90.000000,BMW F 800 GT,09/2018,Gasoline,Manual,Used,NaN,/offers/bmw-f-800-gt-gasoline-white-f65273c6-6...
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,Manual,Used,NaN,/offers/nova-motors-retro-star-gasoline-red-f8...
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,Manual,Used,RF,/offers/aprilia-rsv4-rf-gasoline-silver-1b51fe...
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,Manual,Used,NaN,/offers/kawasaki-ninja-zx-6r-gasoline-blue-2f8...
...,...,...,...,...,...,...,...,...,...,...
34911,36500,7000,90.000000,Harley-Davidson Road Glide,09/2019,Gasoline,Manual,Used,NaN,/offers/harley-davidson-road-glide-gasoline-si...
34912,17300,10592,125.000000,BMW R 1200 RT,04/2018,Gasoline,Manual,Used,R 1200RT LC,/offers/bmw-r-1200-rt-r-1200rt-lc-gasoline-bla...
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,Manual,Used,NaN,/offers/harley-davidson-iron-883-gasoline-blac...
34915,8350,11500,56.000000,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used,Black mit Garantie,/offers/triumph-bonneville-t100-black-mit-gara...
34916,8500,19000,46.000000,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used,NaN,/offers/yamaha-tmax-530-gasoline-black-eeb19fb...

In [22]:
dataset.drop(['version', 'link'], axis = 1, inplace=True)

C:\Users\sony\Anaconda3\envs\AIMLL\lib\site-packages\pandas\core\frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [23]:
dataset

,price,mileage,power,make_model,date,fuel,gear,offer_type
0,23990,150,218.000000,Honda,03/2020,Gasoline,Manual,Demonstration
1,7500,2871,90.000000,BMW F 800 GT,09/2018,Gasoline,Manual,Used
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,Manual,Used
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,Manual,Used
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,Manual,Used
...,...,...,...,...,...,...,...,...
34911,36500,7000,90.000000,Harley-Davidson Road Glide,09/2019,Gasoline,Manual,Used
34912,17300,10592,125.000000,BMW R 1200 RT,04/2018,Gasoline,Manual,Used
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,Manual,Used
34915,8350,11500,56.000000,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used
34916,8500,19000,46.000000,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used

In [24]:
dataset

,price,mileage,power,make_model,date,fuel,gear,offer_type
0,23990,150,218.000000,Honda,03/2020,Gasoline,Manual,Demonstration
1,7500,2871,90.000000,BMW F 800 GT,09/2018,Gasoline,Manual,Used
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,Manual,Used
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,Manual,Used
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,Manual,Used
...,...,...,...,...,...,...,...,...
34911,36500,7000,90.000000,Harley-Davidson Road Glide,09/2019,Gasoline,Manual,Used
34912,17300,10592,125.000000,BMW R 1200 RT,04/2018,Gasoline,Manual,Used
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,Manual,Used
34915,8350,11500,56.000000,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used
34916,8500,19000,46.000000,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used

In [25]:
dataset["make_model"].value_counts()

BMW R 1200 GS              678
BMW R nineT                377
Others                     336
Harley-Davidson Softail    328
Honda                      323
                          ...
Yamaha NEOs Easy             1
Mc Motors                    1
Ride Jump 50                 1
KSR Moto Worx 125            1
Matchless G 12               1
Name: make_model, Length: 2168, dtype: int64

In [26]:
dataset["gear"].value_counts()

Manual            26867
Automatic          1983
Semi-automatic      235
Name: gear, dtype: int64

In [27]:
dataset["fuel"].value_counts()

Gasoline               27952
Two Stroke Gasoline      469
Electric                 374
Others                   148
Diesel                   132
Electric/Gasoline          8
LPG                        2
Name: fuel, dtype: int64

In [28]:
dataset["price"].value_counts()

6000     595
7000     552
9000     427
8000     396
8500     389
        ...
1959       1
5680       1
6475       1
14389      1
51900      1
Name: price, Length: 2505, dtype: int64

In [29]:
dataset["mileage"].value_counts()

0        1577
1         739
10000     232
20000     229
1000      227
         ...
75137       1
14305       1
15856       1
3383        1
9184        1
Name: mileage, Length: 9491, dtype: int64

In [30]:
dataset["offer_type"].value_counts()

Used                 26263
New                   1730
Demonstration          680
Pre-registered         239
Antique / Classic      173
Name: offer_type, dtype: int64

In [31]:
dataset.isnull().sum()

price         0
mileage       0
power         0
make_model    0
date          0
fuel          0
gear          0
offer_type    0
dtype: int64

In [32]:
Bike_df = dataset.copy()

In [33]:
Bike_df

,price,mileage,power,make_model,date,fuel,gear,offer_type
0,23990,150,218.000000,Honda,03/2020,Gasoline,Manual,Demonstration
1,7500,2871,90.000000,BMW F 800 GT,09/2018,Gasoline,Manual,Used
2,800,1700,3.000000,Nova Motors Retro Star,10/2019,Gasoline,Manual,Used
3,14990,24345,206.157598,Aprilia RSV4,03/2016,Gasoline,Manual,Used
4,6200,25000,128.000000,Kawasaki Ninja ZX-6R,08/2009,Gasoline,Manual,Used
...,...,...,...,...,...,...,...,...
34911,36500,7000,90.000000,Harley-Davidson Road Glide,09/2019,Gasoline,Manual,Used
34912,17300,10592,125.000000,BMW R 1200 RT,04/2018,Gasoline,Manual,Used
34913,8500,29000,54.000000,Harley-Davidson Iron 883,05/2004,Gasoline,Manual,Used
34915,8350,11500,56.000000,Triumph Bonneville T100,05/2018,Gasoline,Manual,Used
34916,8500,19000,46.000000,Yamaha TMAX 530,07/2018,Gasoline,Automatic,Used

In [34]:
Bike_df.to_csv("Premotorbike.csv",index=False)